# -*- coding: utf-8 -*-
"""ques3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PInEbI7E2yRpsocn7uBgwSjRrzM4KJCt
"""

#3. KeyError Handler

try:
  my_dict = {"a": 1, "b": 2}
  print(my_dict["c"])
except KeyError:
  print("Error: Key not found in dictionary")